<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-WebLoginFacebook</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cb198e85-ae1c-4179-9898-e30f6153f46f</testSuiteGuid>
   <testCaseLink>
      <guid>5d52a6df-a5f6-4516-b829-e5134fe1804c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Facebook/LoginInvalidEmailOrPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a24d00f-a5aa-4330-b16c-ba70c6167da2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cedb9265-6510-4b18-a07c-09c8ac850611</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Facebook/LoginInvalidTigaKaliAtauLebih</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce4c64dd-000f-4f52-bd7f-936e394b6e2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3640eae-cefe-4091-a65e-c5a48c485058</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Facebook/LoginPageSetelahUserSuccessLogin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c156fee0-f1f9-4e07-b466-98254fce1000</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>effea390-dfa0-4cfa-a256-e95d846b1d39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Facebook/LoginValidSetelahSalahInputEmailOrPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2e28fd5-2b5f-4273-a5f4-e65075f1f301</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca740879-3bbf-4815-8e00-44953d9ba6f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84fa9b8b-c77e-43df-bb6c-37f8a9e6c179</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Facebook/LoginValidUsernameAndPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa8f4155-ca76-410c-b56c-64bb143973ef</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
