<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>borderEmail</name>
   <tag></tag>
   <elementGuidId>2ddb2dcb-7a7f-46a5-89d1-88a14cb4abe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b574c674-dab0-4eb8-8551-ba9b75d6c5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1725545921656</value>
      <webElementGuid>030e2d5f-2336-4710-8edb-33bd39c1b8f3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
