<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove</name>
   <tag></tag>
   <elementGuidId>2fde6288-8aad-4708-b22a-90244b8a8bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._42ft._5upp._50zy.layerCancel._36gl._50-0._50z_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>412b6895-6066-4825-b968-31ec374f8565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _5upp _50zy layerCancel _36gl _50-0 _50z_</value>
      <webElementGuid>ec56b6fa-4c0b-423e-8fcf-4cd986c99db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>737a5bb1-b48a-40fd-8b15-f46c1c8db784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>385566a5-d49e-4ee9-9d6b-a62463e728b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>830220ba-e06a-46f6-9ae9-7c1bbe4ccab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>29a75799-adc1-43f0-bd73-e0a940b4e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_0&quot;)/div[@class=&quot;_53ij&quot;]/div[@class=&quot;_53iv&quot;]/div[@class=&quot;_21es&quot;]/button[@class=&quot;_42ft _5upp _50zy layerCancel _36gl _50-0 _50z_&quot;]</value>
      <webElementGuid>a867db48-f5e4-4273-9dd4-c37f0da54d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d2a14a3b-2499-45bc-924c-d450b3e4924f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js_0']/div/div/div/button</value>
      <webElementGuid>eb5577bb-de38-43fa-be2e-2da6772f8610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rahma'])[1]/following::button[1]</value>
      <webElementGuid>97a7737d-f6ff-434d-bc13-e5563b70ca24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click your picture or add an account.'])[1]/following::button[1]</value>
      <webElementGuid>8ffe7fe5-602e-4ded-a699-79edf4d197bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next time you log in, click your picture. To remove an account from this page, click here.'])[1]/preceding::button[1]</value>
      <webElementGuid>3fa7295e-f6bb-4625-a293-cf51e0e1e1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::button[1]</value>
      <webElementGuid>0d0f54ee-858d-49df-801d-b23a700362b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>505ca484-31dc-4b79-8a60-f159c9b2d29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0c127658-ab78-4b0a-bb9d-6050e61ab339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Remove' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>7052865a-b870-4c34-a527-429e6840bd69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
