<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tooltip</name>
   <tag></tag>
   <elementGuidId>26b6c629-8814-4ecd-9bd9-019fee34d0a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.__xn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js_0']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>169b2cbf-dbe5-4dfb-9adc-26136832d6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__xn</value>
      <webElementGuid>2f7d9579-f634-4bc5-93ba-6b9881ad6d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next time you log in, click your picture. To remove an account from this page, click here.</value>
      <webElementGuid>d622dc9e-e9a4-44b3-bd4b-a6efbcadbcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_0&quot;)/div[@class=&quot;_53ij&quot;]/div[@class=&quot;_53iv&quot;]/div[@class=&quot;_21es&quot;]/div[@class=&quot;__xn&quot;]</value>
      <webElementGuid>c4f8077d-321f-47a9-90d6-6910c2748423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js_0']/div/div/div/div</value>
      <webElementGuid>6af632da-2cdf-4ef3-811e-999b70831d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::div[1]</value>
      <webElementGuid>89c68206-da7d-4f39-abb4-281e589c94d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rahma'])[1]/following::div[7]</value>
      <webElementGuid>fc5c2ec7-3848-4d56-8161-02a25b576ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::div[3]</value>
      <webElementGuid>5ebcb38d-269b-4e73-97d9-b9bad8bbc262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[13]</value>
      <webElementGuid>69be31fb-01c1-4717-9534-35e4a7255b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next time you log in, click your picture. To remove an account from this page, click here.']/parent::*</value>
      <webElementGuid>ab79f028-24f1-4f6b-922d-68833bfaf3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>94802a3d-8d4c-4919-9128-52441ed078bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Next time you log in, click your picture. To remove an account from this page, click here.' or . = 'Next time you log in, click your picture. To remove an account from this page, click here.')]</value>
      <webElementGuid>c24c4103-9621-4c80-9dd9-10311625a211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
